controller_frequency: 5.0
recovery_behaviour_enabled: false

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.04 # A tolerance on the goal point for the planner.