#GlobalPlanner:
#   neutral_cost: 66
#   lethal_cost: 253
#   cost_factor: 0.55

controller_frequency: 5.0
recovery_behaviour_enabled: false

NavfnROS:
  allow_unknown: true
  default_tolerance: 0.04
  planner_window_x: 0.0
  planner_window_y: 0.0
  planner_window_z: 0.0
  potential_scale: 3.0
  orientation_mode: "forward"
  use_quadratic: true
  visualize_potential: false
  cost_factor: 0.55
  default_cost: 254
  unknown_cost: 253
  lethal_cost: 253
  neutral_cost: 66
  publish_potential: false
  allow_negative_cost: true
