global_frame: map
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 0.5 
resolution: 0.03
static_map: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
